GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5Nzg1MDk5NX0.kxGhnkasjr8cMdkIufxnOAYigrzttk5-WEpabQFYs9Y
###


GET http://localhost:3000/tasks
Authorization: Token 
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}
